Module Enumerable ready for code review
tigamadou/my_enumerable pull request #1
Opened 2019-11-26 19:48 UTC by genzaraki

2019-11-26 21:06 UTC, Anna-Myzukina commented
#### Pull Request under the review by Anna Muzykina (TSE)

2019-11-26 21:26 UTC, Anna-Myzukina commented
## Hi Amadou! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Amazing job!

Only one thing needs to be fixed. Please see my comment above


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding *

2019-11-26 21:26 UTC, Anna-Myzukina commented on main.rb
> +  end
[REQUIRED]

Counts method works not correct.

        Failure/Error: expect(array.my_count(LOWEST_VALUE)).to eq 
          array.count(LOWEST_VALUE)
     
                expected: 11
                     got: 100

2019-11-26 21:27 UTC, Anna-Myzukina requested changes
Needs to fix one error in count method

2019-11-26 21:34 UTC, genzaraki commented
count method edited.

2019-11-26 23:59 UTC, Forison approved these changes
## Hi @Amadou,
Good Job on implementing the change suggested by my colleague.
```my_count``` works fine💪 now
### Project is approved🙂
#### Happy coding🙂
#### @Forison

2019-11-27 00:20 UTC, genzaraki commented
@Forison @Anna-Myzukina Thank you very much guys for your commitment 💪 .

2019-11-27 00:21 UTC, merged